### ISSUE TITLE
请问下面这个错误怎么解决？The current Dart SDK version is 2.1.0-dev.3.1.flutter-760a9690c2.

### ISSUE THREAD

**Issue by jinhuizxc** [BakerJQ/Flutter-InfiniteCards#1]
The current Dart SDK version is 2.1.0-dev.3.1.flutter-760a9690c2.

Because InfinateCards requires SDK version >=2.1.0 <3.0.0, version solving failed.
pub get failed (1)

**Comment by BakerJQ** [comment]
更新一下flutter版本试试
$ flutter upgrade
